version: '3.7'
services:

  keycloak:
    image: lapierre/keycloak:21.0.2
    command:
      - start-dev --import-realm --auto-build  --db=postgres
    environment:
      - KC_HOSTNAME=keycloak
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8443:8443"
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"


volumes:
  pg_data:


